### ISSUE TITLE
trying to set currents errors

### ISSUE THREAD

**Issue by pierreberthet** [alejoe91/MEAutility#14]
/media/terror/code/source/MEAutility/MEAutility/core.py in reset_currents(self, amp)
    324         else:
    325             currents = amp*np.ones(self.number_electrode)
--> 326         self.currents(currents)
    327 
    328 

TypeError: 'numpy.ndarray' object is not callable

---------
/media/terror/code/source/MEAutility/MEAutility/core.py in set_current_matrix(self, currents)
    503         #     for zz in range(self.dim):
    504         #         current_array[self.dim * yy + zz] = currents[zz, yy]
--> 505         self.set_currents(currents=np.reshape(currents, self.dim))
    506 
    507 

AttributeError: 'RectMEA' object has no attribute 'set_currents'

**Comment by alejoe91** [comment]
ec4c08a1e22b83993310bcea52aca9c620be5093
