### ISSUE TITLE
plot_3d

### ISSUE THREAD

**Issue by pierreberthet** [alejoe91/MEAutility#15]
when I assign new positions to the electrodes, like 
`for i in range(bisc.get_electrodes_number()):
    bisc.electrodes[i].current = params.sim['ampere']
    bisc.electrodes[i].position[2] = pia_height`
and I then ask for:
`mea.plot_probe_3d(bisc, ax=ax1, xlim=[-300, 300], ylim=[-300, 300], zlim=[np.min(cell.zmid) - 50, 200])
`
the green plane is not aligned (still at z=0) with the electrode plane (correctly at z=pia_height)

**Comment by alejoe91** [comment]
you should use the `move` function instead.

Now you can plot a planar mea with the plot_probe_3d(..., type='planar')

a2c4d22ad2bcd3fcc1a5b9dfc3934939593b9c5c

**Comment by pierreberthet** [comment]
planar mea works, but there is still an offset between electrodes and the
green plane. even with move function.
