### ISSUE TITLE
plotting electrodes

### ISSUE THREAD

**Issue by pierreberthet** [alejoe91/MEAutility#16]
Would not it be fantastic if the MEA plot would color the active electrodes differently from the inactive ones?
currents == 0 Vs currents!= 0
I believe it would be amazing.

**Comment by alejoe91** [comment]
62e198e4d4db7a4c9fb1b38ab49737b806c1e87f

@pierreberthet you can set the argument `color_currents=True` and also choose `cmap` (default is viridis) from plot_probe and plot_probe_3d
