### ISSUE TITLE
electrodes and probe misaligned when mea.move()

### ISSUE THREAD

**Issue by pierreberthet** [alejoe91/MEAutility#19]
after a mea.move([0, 2000, 50]) and a mea.plot_probe_3d() the electrodes (correctly at -2000) are not overlapped by the probe (seems to be at -4000).
Furthermore, the x and y axes (I had set the range of the z axis) are huge: x:[0, -8000] and y:[0, -10000] even though there does not seem to be anything there.

**Comment by alejoe91** [comment]
fixed 5cc2f38be4b192a9aa4084cf294ff9f2bc5f1e44

It was a plotting problem.
