### ISSUE TITLE
mea plot 3d  green? plane not moved in z-axis

### ISSUE THREAD

**Issue by pierreberthet** [alejoe91/MEAutility#20]
Yes. No need to say more. Security issue. Defcon 1.

I believe it is somehow related to mea.move(). The green plane is displayed at z=0, the electrode plane is where it should be. x and y displacement look fine.
Why?

**Comment by alejoe91** [comment]
I'll look into it in 10 min

**Comment by pierreberthet** [comment]
`import MEAutility as mea`
`bisc = mea.return_mea('bisc_4')  # could that be the cause, a bad definition?`
`bisc.move([0,0, 200])`
`from matplotlib import pyplot as plt`
`mea.plot_probe_3d(bisc)`
`plt.show()`

**Comment by pierreberthet** [comment]
bisc_4.yaml:
`electrode_name: bisc_4`
`sortlist: null`
`pitch: 26`
`dim: 4`
`size: 7`
`shape: square`
`plane: xy`
`type: mea`

**Comment by alejoe91** [comment]
Try now!

The problem was only for 'xy' probes

1f75ee918f2e84582d602998ec45be2f1dee64a2

**Comment by pierreberthet** [comment]
black magic! it works! good job!
