### ISSUE TITLE
Create arbitrary electrode layout 

### ISSUE THREAD

**Issue by McD-NMI** [alejoe91/MEAutility#22]
I am trying to create a MEArec file, but I first want to define my MEA geometry with arbitrary locations (no regular pattern). I can not figure out how to create this in MEAutility from the documentation. I was wondering if you might have any insights into how to make this? Would it be possible to import a list of points?

**Comment by alejoe91** [comment]
Hi @McD-NMI 

Unfortunately this is not built-in in MEArec/MEAutility.

You can always instantiate the probe with the positions (2D or 3D), create a mea object, and save it for MEArec to use.

Let's say you have a numpy array or a list with your positions called 'positions' (Nx2 or Nx3)
Then you can create a dictionary and make a MEA object using the MEAutility package (in Python):

```
import MEAutility as mu

probe_info = {'electrode_name': 'my_circular_probe',
                          'description': 'my_description',
                          'pos': positions, 
                          'size': 5,
                          'shape': 'circle'} 
mea_object = mu.return_mea(info=probe_info​)
```

You can see more available parameters [here](https://meautility.readthedocs.io/en/latest/mea_definitions.html).
Now you can add this newly created MEA to the MEAutility library:
```
mu.add_mea(mea_object) # should print the new list of probes
```

As MEArec uses MEAutility, you should see your newly created probe available in MEArec:

`>> mearec available-probes`

And you can now use my_circular_probe as probe. e.g.

`>> mearec gen-templates -prb my_circular_probe `
