### ISSUE TITLE
Problem with 3D electrode grids?

### ISSUE THREAD

**Issue by torbjone** [alejoe91/MEAutility#31]
Hi,
in LFPy, I got an error when I tried to make a 3D grid of electrodes:

"
....
  File "/home/tone/work/LFPykit/lfpykit/models.py", line 841, in __init__
    self.probe = mu.MEA(positions=positions, info=probe_info,
  File "/home/tone/.local/lib/python3.8/site-packages/MEAutility/core.py", line 379, in __init__
    normal /= np.linalg.norm(normal)
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
"
I'm not sure what is causing the error, but an easy fix seems to be to change from
normal /= np.linalg.norm(normal)  
to 
normal = normal / np.linalg.norm(normal)  
at this line:
https://github.com/alejoe91/MEAutility/blob/83e471351158772aadda52ea02157a2fe03cfe96/MEAutility/core.py#L404

Here is a notebook example that reproduces the error locally:
https://www.dropbox.com/s/k22jnskumzi9o9k/LFPy-example-02-Copy1.ipynb?dl=0

Do you also have this issue?

**Comment by alejoe91** [comment]
Thanks @torbjone 

Hope you are doing well :)

I'll try the code later. Can you make a PR in the meanwhile?

**Comment by torbjone** [comment]
I am doing well, thank you, I hope you are doing well as well :-)

PR created.
