### ISSUE TITLE
About 3D grid electrodes

### ISSUE THREAD

**Issue by Vince0226** [alejoe91/MEAutility#40]
Hi, 
Could I build a 3D electrodes in LFPy through MEA? I have read the documentation, but I only found the way of 2D electrodes building which means that put electrodes on same plane.
An idea come to me is build multiple 2D electrodes(xy plane), put them to different position on z-axis and superpose it.
Does it work or can I build 3D directly?
Thanks.

**Comment by alejoe91** [comment]
Hi @Vince0226 

MEAutility supports 3d electrodes natively. Each electrode in fact is represented by 3D positions and these should be used directly by LFPy. 

Did you stumble upon any error?

**Comment by Vince0226** [comment]
I built a general MEA according to documentation, and I still don't know how to build it in 3D version.
Do you have any simple example about 3D electrodes?

**Comment by Vince0226** [comment]
Sorry, I didn't properly describe my question, I renew it. I know that MEAutility can build electrode in 3d position, but I can only build flat electrodes and rotate it. Can MEA build a column of electrodes? For example, Distributing 8 electrodes in a box (Coordinate: [0,0,0], [0,1,0], [0,0,1], [1,0,0], [1,1,0], [0,1,1], [1,0,1], [1,1,1] ).

**Comment by alejoe91** [comment]
Hi @Vince0226 

No, you would have to provide the positions "manually" as the `pos` entry of the dictionary/yaml file.

**Comment by Vince0226** [comment]
OK, I will try it. Thanks for your help.
